### PR TITLE
default statuses & fix for settings (fixes #181)

### LINKED ISSUE #181: Results with statuses 'skipped' and 'unknown' are not shown on xunit tab by default
image

all statuses should be selected by default

### PR DESCRIPTION
**Pull request by ehborisov**

### CODE REVIEW

**Comment by just-boris** [comment]
Actually, the problem was that I have applied plugins in a custom order.
I have added a change that makes it right.

But also it makes sense not to deal with badly documented stuff in favor of explicit coding.

File: allure-web/src/data/settings/SettingsModel.js [hunk 1]
```diff
@@ -1,24 +1,24 @@
...
+            sidebarCollapsed: false,
+            visibleStatuses: {
+                failed: true,
+                broken: true,
+                skipped: true,
+                unknown: true,
+                passed: true
+            },
+            showGroupInfo: true
+        }
```
Comment (just-boris) [inline allure-web/src/data/settings/SettingsModel.js]: missing semicolon

File: allure-web/src/data/settings/SettingsModel.js [hunk 2]
```diff
@@ -1,24 +1,24 @@
-import {Model} from 'backbone';
-import {protoprop} from '../../decorators';
+import {Model} from "backbone";
```
Comment (just-boris) [inline allure-web/src/data/settings/SettingsModel.js]: Strings must use singlequote
