### PR TITLE
Get rid of pending status (fixes #88, fixes #37)

### LINKED ISSUE #37: Fix NPE when test case has null status

### LINKED ISSUE #88: [Model2] Rft statuses
1. status in [failed, broken, skipped, passed, unknown] 
2. lifecycle status in [scheduled, running, finished, (not_run ??)]
3. statusDetails [isKnown, isFlaky, message, trace]

### PR DESCRIPTION
**Pull request by baev**

### CODE REVIEW

File: allure-generator/src/main/java/io/qameta/allure/allure2/StatusDeserializer.java [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+        super(Status.class);
+    }
+
+    @Override
+    public Status deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
+        String value = p.readValueAs(String.class);
+        return Stream.of(Status.values())
+                .filter(status -> status.value().equalsIgnoreCase(value))
+                .findAny()
+                .orElse(null);
```
Comment (sskorol) [inline allure-generator/src/main/java/io/qameta/allure/allure2/StatusDeserializer.java]: you can return `Optional<Status>` instead of `null`;
and callers could handle it much easier than `if (isNull(status)) {...}` via optional operators

File: allure-generator/src/main/java/io/qameta/allure/allure1/Allure1ResultsReader.java [hunk 2]
```diff
@@ -208,6 +208,9 @@ private Attachment convert(ru.yandex.qatools.allure.model.Attachment attachment)
     }
 
     public static Status convert(ru.yandex.qatools.allure.model.Status status) {
+        if (Objects.isNull(status)) {
```
Comment (sskorol) [inline allure-generator/src/main/java/io/qameta/allure/allure1/Allure1ResultsReader.java]: this method's body could be simplified:

```java
ofNullable(status).orElse(UNKNOWN);
```

or even easier, if you return `Optional<Status>`

Comment (sskorol) [inline allure-generator/src/main/java/io/qameta/allure/allure1/Allure1ResultsReader.java]: ah, you have 2 similar `Status` types... thought it's the same status...

File: allure-generator/src/main/java/io/qameta/allure/allure2/StatusDeserializer.java (hunk 1 above)
Comment (baev) [inline allure-generator/src/main/java/io/qameta/allure/allure2/StatusDeserializer.java]: @sskorol no, I can't. The returned value gonna be stored to field with type `Status` in related bean.

File: allure-generator/src/main/java/io/qameta/allure/allure1/Allure1ResultsReader.java (hunk 2 above)
Comment (sskorol) [inline allure-generator/src/main/java/io/qameta/allure/allure1/Allure1ResultsReader.java]: ah, you have 2 similar status types... =\ missed that

**Comment by baev** [comment]
@sskorol if you have no other comments, can you approve it? 😉
