### PR TITLE
overwrite plugin files, require --clean option for existing directory (fixes #264)

### LINKED ISSUE #264: Commandline called twice on same results throws Exception
`$ allure generate target/allure-results`
```
Report successfully generated to allure-report
```

`$ allure generate target/allure-results`
```
Could not generate report: {}
java.nio.file.FileAlreadyExistsException: allure-report/plugins/behaviors/index.js
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:551)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at io.qameta.allure.util.CopyVisitor.visitFile(CopyVisitor.java:35)
	at io.qameta.allure.util.CopyVisitor.visitFile(CopyVisitor.java:15)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at io.qameta.allure.plugin.DefaultPlugin.unpackReportStatic(DefaultPlugin.java:44)
	at io.qameta.allure.core.ReportWebPlugin.writePluginsStatic(ReportWebPlugin.java:48)
	at io.qameta.allure.core.ReportWebPlugin.aggregate(ReportWebPlugin.java:38)
	at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:32)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:49)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:37)
	at io.qameta.allure.Commands.generate(Commands.java:55)
	at io.qameta.allure.CommandLine.run(CommandLine.java:121)
	at java.util.Optional.orElseGet(Optional.java:267)
	at io.qameta.allure.CommandLine.main(CommandLine.java:72)
```

### PR DESCRIPTION
**Pull request by ehborisov**

### CODE REVIEW

File: allure-commandline/src/main/java/io/qameta/allure/Commands.java [hunk 1]
```diff
@@ -47,8 +52,12 @@ public ExitCode generate(final Path reportDirectory,
                              final List<Path> resultsDirectories,
                              final boolean clean,
                              final String profile) {
-        if (clean && Files.exists(reportDirectory)) {
+        final boolean directoryExists = Files.exists(reportDirectory);
+        if (clean && directoryExists) {
```
Comment (baev) [inline allure-commandline/src/main/java/io/qameta/allure/Commands.java]: can you add a test for that case

File: allure-commandline/src/main/java/io/qameta/allure/Commands.java [hunk 2]
```diff
@@ -70,6 +70,10 @@ public ExitCode generate(final Path reportDirectory,
         return ExitCode.NO_ERROR;
     }
 
+    private static boolean directoryIsNotEmpty(final Path reportDirectory) {
+        return Optional.ofNullable(reportDirectory.toFile().list()).map(l -> l.length).orElse(0) != 0;
```
Comment (baev) [inline allure-commandline/src/main/java/io/qameta/allure/Commands.java]: I don't like this logic, you can use `tmp.resolve("allure-report")` in serve command to make sure that directory doesn't exists
