### PR TITLE
Fix unsupported browse operation error (fixes #1122)

### LINKED ISSUE #1122: Got exception when allure open browser
Got this exception when allure trying to open the browser.
```

Exception in thread "main" java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
        at java.awt.Desktop.checkActionSupport(Desktop.java:221)
        at java.awt.Desktop.browse(Desktop.java:380)
        at io.qameta.allure.Commands.openBrowser(Commands.java:213)
        at io.qameta.allure.Commands.open(Commands.java:138)
        at io.qameta.allure.Commands.serve(Commands.java:122)
        at io.qameta.allure.CommandLine.run(CommandLine.java:144)

```
The way allure check if can open browser is supported is different from awt.Desktop.

allure's way:
https://github.com/allure-framework/allure2/blob/59384bd81c6cd82c0258db84885b0b6b5d46ed4d/allure-commandline/src/main/java/io/qameta/allure/Commands.java#L220

awt.Desktop's way
`this.checkActionSupport(Desktop.Action.BROWSE);`

I think it should be the same.

### PR DESCRIPTION
**Pull request by jaimedelreyg**
### Context
Although Desktop.isDesktopSupported() is working well in Java with different desktops (Linux, Windows, Macos), browse operation throws an exception not caught in the code if the current desktop doesn't support it.

Issues related: #1122 

#### Checklist
- [x] [Sign Allure CLA][cla]

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

File: allure-commandline/src/main/java/io/qameta/allure/Commands.java [hunk 1]
```diff
@@ -218,10 +218,12 @@ protected Server setUpServer(final String host, final int port, final Path repor
      */
     protected void openBrowser(final URI url) throws IOException {
         if (Desktop.isDesktopSupported()) {
-            Desktop.getDesktop().browse(url);
-        } else {
-            LOGGER.error("Can not open browser because this capability is not supported on "
+            try {
+                Desktop.getDesktop().browse(url);
+            } catch (UnsupportedOperationException e) {
+                LOGGER.error("Can not open browser because this capability is not supported on "
```
Comment (baev) [inline allure-commandline/src/main/java/io/qameta/allure/Commands.java:224]: Use `LOGGER.error("message", e)`

**Review by baev — APPROVED** [review]

File: allure-commandline/src/main/java/io/qameta/allure/Commands.java (hunk 1 above)
Comment (jaimedelreyg) [reply allure-commandline/src/main/java/io/qameta/allure/Commands.java:224]: Done

Comment (jaimedelreyg) [reply allure-commandline/src/main/java/io/qameta/allure/Commands.java:224]: > 
> 
> Use `LOGGER.error("message", e)`

Done :)

**Comment by baev** [comment]
@jaimedelreyg thanks!
