### PR TITLE
Fix NaN in tooltip text (fixes #156)

### LINKED ISSUE #156: Fix status graph tooltip
screen shot 2017-02-14 at 19 06 59

### PR DESCRIPTION
**Pull request by sseliverstov**

### CODE REVIEW

File: allure-web/src/plugins/graph/charts/StatusChart.js [hunk 1]
```diff
@@ -94,8 +94,10 @@ export default class StatusChart extends BaseChartView {
     }
 
     getTooltipContent({data}) {
+        var value = isNaN(data.value) ? 0 : data.value;
+        var part = isNaN(data.part) ? 0 : data.part;
```
Comment (just-boris) [inline allure-web/src/plugins/graph/charts/StatusChart.js]:
```
var part = data.part || 0;
```
would be enough actually

Comment (sseliverstov) [inline allure-web/src/plugins/graph/charts/StatusChart.js]: change

**Comment by baev** [comment]
@sseliverstov thanks!
