### PR TITLE
Timeline bug in IE (fixes #219)

### LINKED ISSUE #219: Timeline is broken in IE11

### PR DESCRIPTION
**Pull request by sseliverstov**

### CODE REVIEW

File: allure-web/src/app.js [hunk 1]
```diff
@@ -11,6 +11,9 @@ import i18next, { initTranslations } from './util/translation';
 
 Behaviors.behaviorsLookup = behaviors;
 
+//https://github.com/d3/d3-timer/pull/21
+window.requestAnimationFrame = window.requestAnimationFrame.bind(window);
```
Comment (just-boris) [inline allure-web/src/app.js]: Duplication. 
If you will rebase this commit onto latest master, you will see this change already commited.

**Comment by just-boris** [comment]
I see here much more changes, than just bug-fixing. 
Have you decided to redesign timeline?

**Comment by sseliverstov** [comment]
d3 slider instead native input type element and some small changes for brush
